services:
  worker:
    image: ghcr.io/sergiors/conduit:latest
    container_name: conduit
    command: ["conduit", "worker"]
    env_file: .env
    ports:
      - 9090:9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "conduit", "health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  api:
    image: ghcr.io/sergiors/conduit:latest
    container_name: conduit-api
    command: ["conduit", "server"]
    ports:
      - 8080:8080
    env_file: .env
    restart: unless-stopped

volumes:
  redis_data:
