services:
  conduit:
    image: ghcr.io/sergiors/conduit:latest
    container_name: conduit
    command: ["conduit", "start"]
    env_file: .env
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "conduit", "health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  redis_data:
